---

- name: "set Timezone to {{ env_timezone }}"
  command: "timedatectl set-timezone {{ env_timezone }}"

- include: ../../../tasks/set_centos_repos.yml

- name: Install chrony
  yum:
    name: chrony
    state: present

- name: Start chrony CentOS
  service:
    name: chronyd
    state: started
    enabled: yes
