---

- name: "set Timezone to {{ env_timezone }}"
  command: "timedatectl set-timezone {{ env_timezone }}"

- name: Start chrony CentOS
  service:
    name: chronyd
    state: started
    enabled: yes
