---

- name: "set Timezone to {{ env_timezone }}"
  command: "timedatectl set-timezone {{ env_timezone }}"

- name: Install chrony
  zypper:
    name: chrony
    state: present
    update_cache: yes

- name: Start chrony SUSE
  service:
    name: chronyd
    state: started
    enabled: yes
