---

#Copyright 2016 ShapeBlue
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

- name: Install iSCSI target packages
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - targetcli
    - iscsi-initiator-utils
  tags:
    - marvin
    - marvin_iscsi

- name: Load target_core_mod kernel module
  modprobe:
    name: target_core_mod
    state: present
  tags:
    - marvin
    - marvin_iscsi

- name: Load iscsi_target_mod kernel module
  modprobe:
    name: iscsi_target_mod
    state: present
  tags:
    - marvin
    - marvin_iscsi

- name: Ensure configfs is mounted
  mount:
    path: /sys/kernel/config
    src: configfs
    fstype: configfs
    state: mounted
  tags:
    - marvin
    - marvin_iscsi

- name: Ensure iSCSI target service is enabled and started
  systemd:
    name: target
    state: started
    enabled: true
  tags:
    - marvin
    - marvin_iscsi

- name: Create iSCSI storage directory
  file:
    path: /var/iscsi_disks
    state: directory
    mode: '0755'
  tags:
    - marvin
    - marvin_iscsi

- name: Create test iSCSI backstore
  shell: targetcli backstores/fileio create test-lun /var/iscsi_disks/test-lun.img 10G write_back=false
  args:
    creates: /var/iscsi_disks/test-lun.img
  tags:
    - marvin
    - marvin_iscsi

- name: Create iSCSI target
  shell: targetcli iscsi/ create {{ env_iscsi_test_target }}
  register: create_target_result
  failed_when: create_target_result.rc != 0 and 'already exists' not in create_target_result.stderr
  changed_when: create_target_result.rc == 0
  tags:
    - marvin
    - marvin_iscsi

- name: Configure target TPG attributes
  shell: targetcli iscsi/{{ env_iscsi_test_target }}/tpg1 set attribute {{ item }}
  with_items:
    - "authentication=0"
    - "generate_node_acls=1"
    - "cache_dynamic_acls=1"
  register: set_attribute_result
  failed_when: set_attribute_result.rc != 0 and 'Cannot locate' not in set_attribute_result.stderr
  changed_when: set_attribute_result.rc == 0
  tags:
    - marvin
    - marvin_iscsi

- name: Create LUN in target
  shell: targetcli iscsi/{{ env_iscsi_test_target }}/tpg1/luns/ create /backstores/fileio/test-lun
  register: create_lun_result
  failed_when: create_lun_result.rc != 0 and 'already exists' not in create_lun_result.stderr
  changed_when: create_lun_result.rc == 0
  tags:
    - marvin
    - marvin_iscsi

- name: Save targetcli configuration
  shell: targetcli saveconfig
  tags:
    - marvin
    - marvin_iscsi

- name: Open firewall for iSCSI
  firewalld:
    port: 3260/tcp
    permanent: yes
    state: enabled
    immediate: yes
  ignore_errors: yes
  tags:
    - marvin
    - marvin_iscsi
