---
# Playbook: Playwright VM Setup
# Description: Provisions a Debian-based VM with Node.js, Playwright, Chromium,
#              and required dependencies. Also syncs time with the management server
#              and verifies installation.

- name: wait for VM to be alive
  shell: "ping {{ ansible_ssh_host }} -c 1"
  register: pong
  until: pong.rc == 0
  retries: "{{ ssh_retries }}"

- name: Wait for SSH
  local_action: wait_for port=22 host="{{ ansible_ssh_host }}" timeout={{ ssh_retries }} connect_timeout=5

- name: Now I'm connected, get facts
  setup:

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install basic dependencies
  apt:
    name:
      - curl
      - wget
      - git
      - gnupg
      - ca-certificates
      - sshpass
    state: present
  when: ansible_os_family == "Debian"

- name: Add NodeSource repository
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  when: ansible_os_family == "Debian"

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Verify Node.js installation
  command: node --version
  register: node_version
  changed_when: false

- name: Verify npm installation
  command: npm --version
  register: npm_version
  changed_when: false

- name: Install Playwright system dependencies
  apt:
    name:
      - libnss3
      - libnspr4
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libdrm2
      - libdbus-1-3
      - libxkbcommon0
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxrandr2
      - libgbm1
      - libasound2
      - libpango-1.0-0
      - libcairo2
      - libatspi2.0-0
      - fonts-liberation
      - libappindicator3-1
      - xvfb
    state: present
  when: ansible_os_family == "Debian"

- name: Install Playwright globally
  npm:
    name: playwright
    global: yes
    state: present

- name: Install Playwright Chromium browser
  shell: npx playwright install chromium --with-deps
  environment:
    PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright

- name: Create test directory
  file:
    path: /playwright
    state: directory
    mode: '0755'

- name: sync time with mgmt server
  shell: date --set=`sshpass -p 'P@ssword123' ssh -o StrictHostKeyChecking=no root@{{ hostvars[groups['primary_cs_manager'][0]]['ansible_ssh_host'] }} 'date --iso-8601=seconds'`
  ignore_errors: yes

- name: Display Playwright VM configuration
  debug:
    msg:
      - "=========================================="
      - "Playwright VM Ready!"
      - "=========================================="
      - "Node.js: {{ node_version.stdout }}"
      - "npm: {{ npm_version.stdout }}"
      - "VM IP: {{ ansible_ssh_host }}"
      - "Test directory: /playwright"
      - "=========================================="
