---

#Copyright 2016 ShapeBlue
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

- name: install Java 1.6 when running cs4.3 or earlier
  yum: name=java-1.6.0-openjdk state=present
  when: env_numversion | version_compare('4.3','<=')

- name: set host to use Java 1.6
  shell: alternatives --set java /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java
  when: env_numversion | version_compare('4.3','<=')

- name: Ensure MySQL Client is present (centos/rhel6)
  yum: name=mysql state=present
  when: ansible_distribution_major_version == "6"

- name: download installer
  get_url: url="{{ sb_repo }}/ccp/{{ccp_install_tarball}}.tar.gz" dest="/tmp/{{ ccp_install_tarball }}.tar.gz"

- name: extract tarball
  unarchive: src="/tmp/{{ ccp_install_tarball }}.tar.gz" dest=/tmp copy=no

#- name: enable base repo
#  set_fact: base_repo_enabled=1
#- template: src=CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo

- name: run installer -- THIS IS VERY FRAGILE
  shell: "cd /tmp/{{ ccp_install_tarball }} && bash ./install.sh -m -s"
  when: env_numversion | version_compare('4.11','<')

- name: run installer -- THIS IS VERY FRAGILE
  shell: "cd /tmp/Rovius-CloudPlatform* && bash ./install.sh -m -s"
  when: env_numversion | version_compare('4.11','>=')




#- name: disable base repo
#  set_fact: base_repo_enabled=0
#- template: src=CentOS-Base.repo.j2 dest=/etc/yum.repos.d/CentOS-Base.repo

#- name: rename CloudStack title in browser
#  shell: sed -i "/document.title =/ c\        document.title = \"{{ env_name_clean }}\";" /usr/share/cloudstack-management/webapps/client/scripts/cloudStack.js
#  tags:
#    - "rename_browser"

#- name: re-gzip file
#  shell: gzip -cf /usr/share/cloudstack-management/webapps/client/scripts/cloudStack.js > /usr/share/cloudstack-management/webapps/client/scripts/cloudStack.js.gz
#  tags:
#    - "rename_browser"

- include: ./setupdb.yml
