---
- name: Configure libvirt security driver to apparmor
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    regexp: '^\s*security_driver\s*='
    line: 'security_driver = "apparmor"'
    state: present
  when: ansible_distribution in ["SUSE", "Ubuntu", "Debian"]
  ignore_errors: true

- name: Configure libvirt security driver to selinux
  lineinfile:
    dest: /etc/libvirt/qemu.conf
    regexp: '^\s*security_driver\s*='
    line: 'security_driver = "selinux"'
    state: present
  when: ansible_distribution in ["CentOS", "Red Hat Enterprise Linux"]
  ignore_errors: true
