---

- name: install SDC
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - numactl
    - libaio
    - sysfsutils
  tags:
    - powerflex
    - SDC

- name: install SDC
  yum:
    name: "{{ env_sdc_binary_url }}"
    state: present
#  when: 
  tags:
    - powerflex
    - SDC

- name: add SDCs to MDMs
  shell: "scli --login --username {{ env_powerflex_mdm_user }} --password '{{ env_powerflex_mdm_password }}' --native_authentication || true;scli --add_sdc --sdc_ip {{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"

  delegate_to: "{{ groups['powerflex_mdm_hosts'][0] }}"
  ignore_errors: True
  tags:
    - powerflex
    - SDC

- name: add MDMs to SDCs
  shell: "/opt/emc/scaleio/sdc/bin/drv_cfg --add_mdm --ip {{ env_powerflex_mdms }}"
  tags:
    - powerflex
    - SDC
