---

- name: wait for VM to be alive
  shell: "ping {{ ansible_ssh_host }} -c 1"
  register: pong
  until: pong.rc == 0
  retries: "{{ ssh_retries }}"
  
- name: Wait for SSH
  local_action: wait_for port=22 host="{{ ansible_ssh_host }}" timeout={{ ssh_retries }} connect_timeout=5
  tags:
    - kvm

- name: Now I'm connected, get facts
  setup:
  tags:
    - kvm

- include: upgrade_centos_kvm.yaml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: upgrade_ubuntu_kvm.yaml
  when: ansible_distribution == 'Ubuntu'

- include: upgrade_debian_kvm.yaml
  when: ansible_distribution == 'Debian'
