---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check groupvars/all file version
      fail: msg="groupvars/all file version is too low.  Please update to latest"
      when:  ("{{ all-file_version|int }}" < 5 )

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Ensure cmk is pointing to the right env
      shell: cmk set profile cloudstack

    - name: Capture build date
      set_fact: env_builddate="{{lookup('pipe','date +%d/%m/%y_%H:%M')}}"

    - name: Request and return environment details
      env_db_manage: DBHOST={{ env_db_ip }} DBUSER={{ env_db_user }} DBPASS={{ env_db_password }} DBNAME={{ env_db_name }} ENV_UUID={{ env_uuid }} ENV_NAME={{ env_name_clean }} ENV_ZONETYPE={{ env_zonetype }} ENV_SECGROUPS={{ env_zone_secgroups }} ENV_COMMENT='{{ env_comment | regex_replace(' ', '_') }}' ENV_ACTION=req

    - name: Check environment variables returned ok
      fail: msg="No environments configurations available - {{ env_return }} {{ env_retmsg }}."
      when: env_return != "success"

    - name: Update group vars file with environmemt details for reference
      lineinfile:
        dest="group_vars/{{ env_name_clean }}"
        insertafter="^env_hv.*$"
        line="{{ item }}"
      with_items:
        - "env_builddate: \"{{ env_builddate }}\""
        - "env_pubvlan: \"{{ env_pubvlan }}\""
        - "env_pubgw: \"{{ env_pubgw }}\""
        - "env_pubmask: \"{{ env_pubmask }}\""
        - "env_pubendip: \"{{ env_pubendip }}\""
        - "env_pubstartip: \"{{ env_pubstartip }}\""
        - "env_podvlans: \"{{ env_podvlans }}\""
        - "env_podgw: \"{{ env_podgw }}\""
        - "env_podmask: \"{{ env_podmask }}\""
        - "env_podendip: \"{{ env_podendip }}\""
        - "env_podstartip: \"{{ env_podstartip }}\""
        - "env_guestnetstartip: \"{{ env_guestnetstartip }}\""
        - "env_guestnetendip: \"{{ env_guestnetendip }}\""
        - "env_guestnetmask: \"{{ env_guestnetmask }}\""
        - "env_guestnetgw: \"{{ env_guestnetgw }}\""
        - "env_guestnetvlan: \"{{ env_guestnetvlan }}\""

# Create build project if it doesn't exist.
    - name: Create project
      include: tasks/updateproject.yml project_tag=Deploying_VMs

    - name: Capture all accounts in domain
      shell: cmk listAccounts listall=true state=enabled | jq -c -r '.account[] | select(.domain == "ROOT")' | jq -c -r '.name' | sed -e ':a;N;$!ba;s/\n/,/g'
      register: allaccts_retval

    - name: get projectid
      shell: cmk listProjects | jq -c '.project[] | select(.name | contains("{{ build_project }}"))' | jq '.id'
      register: projectid

    - name: Add accounts to project
      shell: "cmk addAccountToProject account={{ item }} projectid={{ projectid.stdout }}"
      with_items:
        - "{{ allaccts_retval.stdout.split(',') }}"
      ignore_errors: true

    - name: Build VMs
      include: ./tasks/buildvms_custom_allocator.yml
      when: use_custom_allocator and (use_external_hv_hosts|bool == false)

    - name: Build VMs
      include: ./tasks/buildvms.yml
      when: (use_custom_allocator|bool == false) and (use_external_hv_hosts|bool == false)







## Configure Marvin host

- hosts: marvin_host
  gather_facts: no
  vars:
    num_marv_hosts: "{{ groups['marvin_host'] | length }}"
    num_db_hosts: "{{ groups['mysql_hosts'] | length }}"
  roles:

    - { role: timezone, when: num_marv_hosts | int != 0 and (additional_pod|bool == False) }
    - { role: cloudmonkey, when: num_marv_hosts | int != 0 and (additional_pod|bool == False) }
    - { role: marvin, when: num_marv_hosts | int != 0  and (additional_pod|bool == False) }

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Report all built hosts
      debug: msg="{{ item }} ansible_ssh_host={{ hostvars[item]['ansible_ssh_host'] | default( '<undefined>' ) }}"
      with_items:
        - "{{ groups[ env_name_clean ] }}"


## Run Marvin Tests

- hosts: marvin_host
  gather_facts: no
  tasks:

  - name: Set component tests to run
    shell: "echo /marvin/componenttests-{{ env_name_clean }}.sh | at now + 1 min"
    tags:
      - marvin
      - run_component_tests
    when: run_component_tests

  - name: Set smoke tests to run
    shell: "echo /marvin/smoketests-{{ env_name_clean }}.sh | at now + 1 min"
    tags:
      - marvin
      - run_smoke_tests
    when: run_smoke_tests
